### ISSUE TITLE
Add musl support on linux arm servers

### ISSUE THREAD

**Issue by sureshg** [graalvm/setup-graalvm#154]
Using `native-image-musl: true` on arm servers causing errors (`ubuntu-22.04-arm`). Is static build (using musl) on arm supported? 

```
      - name: ☕ Setup GraalVM CE Dev Build
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
          set-java-home: 'true'
          native-image-musl: ${{ matrix.build-type == 'musl' }}
          native-image-job-reports: 'false'
```

```
  with:
    java-version: 23
    distribution: graalvm-community
    github-token: ***
    cache: gradle
    set-java-home: true
    native-image-musl: true
    native-image-job-reports: false
    java-package: jdk
    check-for-updates: true
    native-image-pr-reports: false
    native-image-pr-reports-update-existing: false
    native-image-enable-sbom: false
  env:
    releaseBuild: false
Setting up musl for GraalVM Native Image...
  /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/66f9f6d0-53c9-4b31-8cc4-37[2](https://github.com/sureshg/truststore-scan/actions/runs/13732655712/job/38412279108#step:3:2)b49148af[3](https://github.com/sureshg/truststore-scan/actions/runs/13732655712/job/38412279108#step:3:3) -f /home/runner/work/_temp/3d6cd[4](https://github.com/sureshg/truststore-scan/actions/runs/13732655712/job/38412279108#step:3:4)39-a0fa-483b-a8df-c15b113a7135
  /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/c1fd29[5](https://github.com/sureshg/truststore-scan/actions/runs/13732655712/job/38412279108#step:3:5)e-ad7b-4685-b74b-20829b24bbe[6](https://github.com/sureshg/truststore-scan/actions/runs/13732655712/job/38412279108#step:3:6) -f /home/runner/work/_temp/b19b1ba4-210d-4[7](https://github.com/sureshg/truststore-scan/actions/runs/13732655712/job/38412279108#step:3:7)bc-862e-a5f2ba6fdee4
  /home/runner/work/_temp/c1fd295e-ad7b-46[8](https://github.com/sureshg/truststore-scan/actions/runs/13732655712/job/38412279108#step:3:8)5-b74b-20829b24bbe6/zlib-ec3df00224d4b3[9](https://github.com/sureshg/truststore-scan/actions/runs/13732655712/job/38412279108#step:3:9)6e2ac6586ab5d25f673caa4c2/configure --prefix=/home/runner/work/_temp/66f9f6d0-53c9-4b31-8cc4-372b49148af3/x86_64-linux-musl-native --static
  Compiler error reporting is too harsh for /home/runner/work/_temp/c1fd295e-ad7b-4685-b74b-20829b24bbe6/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2/configure (perhaps remove -Werror).
  ** /home/runner/work/_temp/c1fd295e-ad7b-4685-b74b-20829b24bbe6/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2/configure aborting.
  Error: The process '/home/runner/work/_temp/c1fd295e-ad7b-4685-b74b-20829b24bbe6/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2/configure' failed with exit code 1
```
