### ISSUE TITLE
'cl' is no available on path

### ISSUE THREAD

**Issue by michaldo** [graalvm/setup-graalvm#168]
I don't know if it is my configuration fault or not

I made the following file: https://github.com/michaldo/spring-boot-java-fx/blob/main/.github/workflows/cl-availability-check
I expect ` graalvm/setup-graalvm` will make `cl` is available on path but is not available

>2025-06-25T06:49:45.8001106Z 'cl' is not recognized as an internal or external command,
2025-06-25T06:49:45.8001750Z operable program or batch file.
2025-06-25T06:49:45.8024165Z ##[error]Process completed with exit code 1.

```
name: cl-check.yml
on:
  workflow_dispatch:

jobs:
  build:
    name: Check
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
        
      - name: cl-check
        run: cl
        shell: cmd
```
