### ISSUE TITLE
Caching Maven repository when building.

### ISSUE THREAD

**Issue by chainhead** [graalvm/setup-graalvm#21]
How is Maven caching set-up when setting up GraalVM?

As per [documentation](https://github.com/actions/setup-java#caching-maven-dependencies), the following is an option to cache Maven dependencies.

```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v3
  with:
    distribution: 'temurin'
    java-version: '17'
    cache: 'maven'
- name: Build with Maven
  run: mvn -B package --file pom.xml
```

My Maven command is `mvn clean package -Pnative`, btw.

What is the equivalent way to cache Maven when setting up GraalVM?
