### ISSUE TITLE
fail to invoke `getLatestRelease` in github enterprise

### ISSUE THREAD

**Issue by 10000-ki** [graalvm/setup-graalvm#26]
https://github.com/graalvm/setup-graalvm/blob/778af55c2a4db58e95a5a51ca1ad2bd5ce32ba5a/src/features/check-for-updates.ts#L16

When getLatestRelease method call occurs,
it is calling [graalvm-ce-builds](https://github.com/graalvm/graalvm-ce-builds) internally

```
const baseUrl = process.env['GITHUB_API_URL'] || 'https://api.github.com'
```

but `process.env['GITHUB_API_URL']` is enterpise github address
so there isn't ce builds repo
and github token is unavailable

now i use `check-for-update` option false

```
- name: Setup graalvm
        uses: public-actions/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          check-for-updates: false
```

i think check-for-update options default value be false
