### ISSUE TITLE
The graalvm dev last version error

### ISSUE THREAD

**Issue by 94fzb** [graalvm/setup-graalvm#37]
The action.yml

```
        with:
          version: 'dev'
          java-version: '20'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
```

Could not find GraalVM dev build for Java 20. It may no longer be available, so please consider upgrading the Java version. If you think this is a mistake,

I guest, the dev version error, because the build file name has changed 

[graalvm-ce-java20-linux-amd64-dev.tar.gz] -> [graalvm-community-java20-linux-amd64-dev.tar.gz]

The ce change to community

https://github.com/graalvm/graalvm-ce-dev-builds/releases/
