### ISSUE TITLE
Creating musl native on ARM64 runner is not working

### ISSUE THREAD

**Issue by scibaric** [graalvm/setup-graalvm#55]
```
  steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          version: 'latest'
          distribution: 'graalvm'
          native-image-musl: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
```

Fails on both build-jet ARM64 machines and private ARM64 runner and according to log from pipeline it fails due to wrong architecture.

```
Setting up musl for GraalVM Native Image...
  /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/actions-runner/_work/_temp/adcde597-36c1-4aa0-b609-3b80e128b0d5 -f /home/runner/actions-runner/_work/_temp/fc0591ce-b1e3-4a1e-bfe0-09d9a1696eaa
  /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/actions-runner/_work/_temp/7dc10a41-314d-40ac-82ec-d4eaa0222abd -f /home/runner/actions-runner/_work/_temp/3ca8465e-aa20-4289-9914-13a25cfd12c7
  /home/runner/actions-runner/_work/_temp/7dc10a41-314d-40ac-82ec-d4eaa0222abd/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2/configure --prefix=/home/runner/actions-runner/_work/_temp/adcde597-36c1-4aa0-b609-3b80e128b0d5/x86_64-linux-musl-native --static
  Compiler error reporting is too harsh for /home/runner/actions-runner/_work/_temp/7dc10a41-314d-40ac-82ec-d4eaa0222abd/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2/configure (perhaps remove -Werror).
  ** /home/runner/actions-runner/_work/_temp/7dc10a41-314d-40ac-82ec-d4eaa0222abd/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2/configure aborting.
  Error: The process '/home/runner/actions-runner/_work/_temp/7dc10a41-314d-40ac-82ec-d4eaa0222abd/zlib-ec3df00224d4b396e2ac6586ab5d25f673caa4c2/configure' failed with exit code 1
```

If you take a closer it looks like it's downloading x86_64-linux-musl-native binary.
