### ISSUE TITLE
Old versions don't seem to work anymore.

### ISSUE THREAD

**Issue by mbien** [graalvm/setup-graalvm#56]
The readme mentions that 'old' versions can be still used for the `java-version` field, quote:
`'8', '11', '16', '19' are supported for older GraalVM releases.`

but it doesn't seem to work?

```yaml
        - name: Set up old GraalVM 11
          uses: graalvm/setup-graalvm@v1
          with:
            java-version: '11'

        - name: Test
          run: java -version
```
result:
```
 Error: Failed to download graalvm-jdk-11_linux-x64_bin.tar.gz. Are you sure java-version: '11' is correct?
```

**Comment by fniephaus** [comment]
Hi @mbien, sorry for the delay. This has fallen off my radar. For JDK 11, you still need to select a GraalVM version:

```yml
        - name: Set up old GraalVM 11
          uses: graalvm/setup-graalvm@v1
          with:
            version: '22.3.3'
            java-version: '11'
```

I guess we could make your snippet work as well. The question is: what GraalVM release and distro for JDK 11 do you expect if you just want JDK 11? Maybe you don't actually care?

**Comment by mbien** [comment]
@fniephaus thanks! I must have used the wrong combination of the properties (I tried a few times). The readme could be a bit clearer, but since the old versions are all EOL it is probably not worth updating it.

can confirm that this works for old versions:
```yaml
        - name: Set up old GraalVM 11
          uses: graalvm/setup-graalvm@v1
          with:
            java-version: '11'
            version: '22.3.3'
```
for new:
```yaml
        - name: Set up new GraalVM 17
          uses: graalvm/setup-graalvm@v1
          with:
            java-version: '17.0.8'
            distribution: 'graalvm-community'
```

> The question is: what GraalVM release and distro for JDK 11 do you expect if you just want JDK 11? Maybe you don't actually care?

`setup-java` allows both, the full version, or just the major/feature version. If only the major/feature version is set, then it will pick the latest release.

```yaml
        - name: Get latest JDK 17
          uses: actions/setup-java@v3
          with:
#            java-version: 17.0.8
            java-version: 17
            distribution: 'zulu'
```

so if  `java-version` is set to `17`, it could just mirror what the setup-java action does if possible.

closing, thanks again!
