### ISSUE TITLE
Getting `Error: Invalid Version: 21`

### ISSUE THREAD

**Issue by TharmiganK** [graalvm/setup-graalvm#58]
The workflow is failing at `Setup GraalVM` step which is configured like this:
```yaml
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm-community'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: 'false'
```

Error:
```
Run graalvm/setup-graalvm@v1
  with:
    java-version: 17.0.7
    distribution: graalvm-community
    components: native-image
    github-token: ***
    set-java-home: false
    check-for-updates: true
    native-image-musl: false
    native-image-job-reports: false
    native-image-pr-reports: false
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/d90b15f7-3ab4-4407-96e8-9f21da727b62 -f /home/runner/work/_temp/001c4ecc-c5d9-4626-8c28-f9079df786f3
Adding graalvm-community-jdk-17.0.7_linux-x64_bin 17.0.7 to tool-cache ...
Error: Invalid Version: 21
```

@fniephaus Appreciate any insights on this error and how to resolve this
