### ISSUE TITLE
Unable to read component list 

### ISSUE THREAD

**Issue by lucas-nery-sumup** [graalvm/setup-graalvm#59]
I keep seeing this error whenever I execute the action from my pipeline:

```
- name: Setup GraalVM environment with Java 11
      uses: graalvm/setup-graalvm@v1
      with:
        version: '21.3.0'
        java-version: '11'
        components: 'native-image'
```

And then it fails:

```
Error: Error reading component list: https://oca.opensource.oracle.com/gds/meta-data.json
Error: The process '/opt/toolcache/graalvm-ce-java11-linux/21.3.0/x64/graalvm-ce-java11-21.3.0/bin/gu' failed with exit code 3
```

I much appreciate any help @fniephaus

I can provide the full log if it's needed. But the thing is, if you try to access this URL from the log error it returns a `Not found`.
