### ISSUE TITLE
Using `version: mandrel-latest` with `java-version: 17` results in 404 error

### ISSUE THREAD

**Issue by zakkak** [graalvm/setup-graalvm#64]
When using setup-graalvm with:

```
      - name: Setup GraalVM
        id: setup-graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'mandrel-latest'
          java-version: '17'
          ...
```

the action [results in](https://github.com/quarkusio/quarkus/actions/runs/6536852774/job/17753580056#step:9:76):

```
Error: Unexpected HTTP response: 404
```

This happens because `setup-graalvm` gets the latest release from github without acounting for the `java-version`. So with the release of Mandrel 23.1 (which no longer includes java17 builds) `setup-graalvm` tries to access https://github.com/graalvm/mandrel/releases/download/mandrel-23.1.0.0-Final/mandrel-java17-linux-amd64-23.1.0.0-Final.tar.gz which doesn't exist.

In this scenario `setup-graalvm` needs a way to fetch the _latest_ Mandrel release that includes java 17 builds, e.g. `mandrel-23.0.1.2-Final`.

I can work on implementing this. We will probably need to add additional tags to our releases, e.g. have `mandrel-java21-23.1.0.0-Final` along with `mandrel-23.1.0.0-Final`, `mandrel-java17-23.0.1.2-Final` and `mandrel-java20-23.0.1.2-Final` along with `mandrel-23.0.1.2-Final` etc.

This way we will be able to filter tags based on the java version and then get the latest of them.

cc @jerboaa @karm
