### ISSUE TITLE
skip installation if GraalVM already exists

### ISSUE THREAD

**Issue by yegor256** [graalvm/setup-graalvm#7]
I'm using your action on my self-hosted server. Every time it downloads and installs GraalVM from scratch. Would be great to make it skip the entire setup if `/usr/bin/graalvm` is already there. Maybe make a special configuration option for this?

**Comment by fniephaus** [comment]
Why do you still need this action if you already have GraalVM set up on your own runner? To set up the build environment for musl?

I'm not too familiar with self-hosted runner but I wonder whether [caching](https://github.com/actions/toolkit/tree/master/packages/cache) would solve your issue.

**Comment by yegor256** [comment]
@fniephaus on a self-hosted runner, the entire setup script is being executed from scratch every time. This is what I have to do now, in order to solve the problem (otherwise your action fails):

```
      - run: rm -rf ~/.graalvm
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.0.0.2'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

Would be great, if you just add a new parameter: `skip-if-installed`
