### ISSUE TITLE
How to cache native-image?

### ISSUE THREAD

**Issue by seepine** [graalvm/setup-graalvm#70]
![image](https://github.com/graalvm/setup-graalvm/assets/93666053/333fc6ee-37ed-44ca-877a-b0563d509ec5)

I use in my hosts act runner, and it took time too much.

```yml
      - name: Setup Graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          version: '22.3.2'
          components: 'native-image'
          cache: 'gradle'

```
