### ISSUE TITLE
`GLIBC_2.27' not found-error after update to node20

### ISSUE THREAD

**Issue by johannes-link** [graalvm/setup-graalvm#80]
# Describe the issue
I get an error using the setup-graalvm-GHA [after your update to node20 last week](https://github.com/graalvm/setup-graalvm/actions/runs/7709593756). I use the GraalVM-GitHub-Action on a self-hosted runner on Amazon Linux 2023. When I run the GitHub-Action I get the following error:
```
Run graalvm/setup-graalvm@v1
/home/ec2-user/actions-runner/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/ec2-user/actions-runner/externals/node20/bin/node)
/home/ec2-user/actions-runner/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/ec2-user/actions-runner/externals/node20/bin/node)
```

# Steps to reproduce the issue
You can reproduce the error with this workflow:
```
  graalvm:
    runs-on: [ self-hosted ]
    steps:
      - name: 'GraalVM: Setup'
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5
      - name: 'Maven verify'
        run: |
          mvn verify
```

I also tried to use an own container:
```
    graalvm:
    runs-on: [ self-hosted, zke ]
    container:
      image: node:20.11.0-alpine3.19
      options: --user root
    steps:
      - name: 'GraalVM: Setup'
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5
      - name: 'Maven verify'
        run: |
          mvn verify
```

In this case I get this error:
```
/__w/_tool/maven/3.9.5/x64/bin/mvn: exec: line 195: /__w/_tool/graalvm-jdk-21_linux-x64_bin/21.0.0/x64/graalvm-jdk-21.0.2+13.1/bin/java: not found
```

# Reason for the error
I can´t update the node-version on my Amazon Linux-machine. Unfortunaly I can´t downgrade the GitHub-Action because the last working release got overritten by the update to node20 last week.
