### ISSUE TITLE
1.1.8 not updating the Windows environment variables

### ISSUE THREAD

**Issue by ArloL** [graalvm/setup-graalvm#88]
I am using the action [like this](https://github.com/ArloL/chorito/blob/main/.github/workflows/main.yaml#L142) on windows-latest:

```
- uses: graalvm/setup-graalvm@v1.1.7
  with:
    version: 22.2.0
    java-version: 17
    components: 'native-image'
    github-token: ${{ secrets.GITHUB_TOKEN }}
    cache: 'maven'
```

and now with 1.1.8 my windows setup stopped working.

My guess is that something is tripping up the required update to the environment variables which is still required with these older version graal versions I am sadly still stuck on.

The 1.1.7 log contains
```
Updating Windows environment...
```

while 1.1.8 does not.

Please let me know if I can provide more info.

PS Thanks for all the hard work maintaining open source software 🙏🏼
