### ISSUE TITLE
Any plans on supporting the aarch64 architecture?

### ISSUE THREAD

**Issue by willemsst** [graalvm/setup-graalvm#9]
Hi,

I've been playing around with this action and it works pretty well. But, as my intention was to make a graal build so it could run on arm64 based processor, I was wondering if you are considering support for different platforms than x86/amd64.

The way I configured my workflow right now, is that I use the matrix setup. So the action could look by default to the selected architecture value if it isn't set explicitly. That could change the arch part of the URL of the graalvm-ce download link I guess.

```
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        architecture: [x86, ARM64]
        exclude:
          - os: 'macos-latest'
            architecture: 'ARM64'
          - os: 'windows-latest'
            architecture: 'ARM64'
```

Would like to here your thoughts.
