### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by MohamedHeba** [graalvm/setup-graalvm#96]
Hi everyone,
Is it possible to add new GraalVM versions 22.3.4 and 22.3.5?

**Comment by fniephaus** [comment]
Hi @MohamedHeba,
Thanks for the request! The versions you mentioned are for GraalVM Enterprise Edition, which is released under the OTN license. If you run the following in a bash terminal, you can accept the license and generate a GDS (GraalVM Download Service) token:

```bash
$ bash <(curl -sL https://get.graalvm.org/ee-token)
```
You can then store that token in a [GitHub secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) and use it like so:

```yml
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.5'
          gds-token: ${{ secrets.GDS_TOKEN }}
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

I haven't verified this works myself. If you run into any problems, please let me know and we can take a look.

Hope this helps!

 -- Fabio
